### ISSUE TITLE
Don't forget to attribute OpenStreetMap

### ISSUE THREAD

**Issue by thibaultmol** [honzaap/Pathfinding#2]
Hey, very cool project btw!
I think your project is using OSM, right?
Don't forget to add a little text box in the bottom right to make it clear that the tiles (and I assume the map data for the routing as well?) is OpenStreetMap

(I think you're using mapbox, which uses Openstreetmap and usually automatically puts a textbox there, so not sure what you need to do to make it appear correctly)

**Comment by honzaap** [comment]
Thank you for pointing that out, I completely missed that. Fixed in a38314553f89018a1c3c2f79d65611702996c6b1.

**Comment by thibaultmol** [comment]
Awesome, thx for the quick fix. Again, very cool project!
