### ISSUE TITLE
enable the user to choose which road network to use

### ISSUE THREAD

**Issue by idshklein** [honzaap/Pathfinding#3]
hi, 
@gboeing in osmnx enables a choice of different street networks when query overpass api:
https://github.com/gboeing/osmnx/blob/9fd590117d459d74065f32de9d64a6abffe2e3f0/osmnx/_overpass.py
I think that enabling geoff's queries in 
https://github.com/honzaap/Pathfinding/blob/a38314553f89018a1c3c2f79d65611702996c6b1/src/api.js#L7C1-L7C1
will help users to visualize different usecases.

**Comment by honzaap** [comment]
Hi, I don't think that this feature would be interesting to use. I am ok with the way it is now.
