### ISSUE TITLE
A* Algorithm correction on distance calculations

### ISSUE THREAD

**Issue by nicogs** [honzaap/Pathfinding#5]
Hi,

I'm working on a version to specifically visualise the A star algorithm with similar data and noticed that the results where sometimes very different, even when I removed the additional weights I added based on maxSpeed & disregarded one way edges. 

That's when I realised you are currently using the Math.hypot() on the difference in longitude and latitude between two nodes. The thing is that the distance in meters between the latitude lines is always the same, the distance in longitude changes. 

Around the equator, 1 degree longitude and latitude is basically the same in distance, for which Math.hypot() will give you the correct distance between two points.
In Finland on the other hand, moving 1 degree left or right (east or west) we only move half the distance of moving 1 degree up or down (north or south). 

=> 
This is why the A* algorithm will heavily favour any movement left or right. 
Using current Math.hypot() for the distance from Point A(Lat 0, Lon 0) & Point B(Lat 0, Lon 1) is the same as the distance between Point A(Lat 88, Lon 88) & Point B(Lat 88, Lon 89), although the actual distance is 348 times bigger.
 
To fix this you should scale by the cosine of the latitude

**Comment by honzaap** [comment]
Hi, thank you , but I don't think that the error is big enough for this to actually matter. Given that the maximum radius is 20km, the margin of error is pretty insignificant and the results are good enough.

**Comment by nicogs** [comment]
The radius isn't what makes the difference, it's calculating the distance between two points by taking the square root of A + B where B will always be half of it's sice. The same for the heuristics. London which is the default map location for example. 

The error is more than big enough to be noticeable in this very zoomed in example of london:
As you can see here, if the A* Algorithm is correctly applied the line should continue as the distance to the end is getting lower &  while the cost is getting higher,but almost as a straight line, so the total should be lower than any other possibility further away from the end
 ![image](https://github.com/honzaap/Pathfinding/assets/64304752/bb342f13-621c-446c-9b74-6166f5b0d102)

But what happens, it stopped, to try a path with a larger distance to the end (that goes down) and then try another path with an equal cost but a longer distance to the end. Which should not happen using the A*   ![image](https://github.com/honzaap/Pathfinding/assets/64304752/38b5afa8-ed10-4f8a-a839-432c7eb52d91)

If you would map out the nodes on a canvas with pixels you can see how the nodes are stretched out because of this.

**Comment by honzaap** [comment]
It's good enough so I think I can live with that.
