### ISSUE TITLE
How to create rute in Indonesian

### ISSUE THREAD

**Issue by wawanfirgiawan** [honzaap/Pathfinding#6]
Please, you can tutorial to add rute in indonesia.

**Comment by honzaap** [comment]
What do you mean? Can you elaborate?

**Comment by wawanfirgiawan** [comment]
Yes, i want to elaborate to create dataset using Indonesian rute

Pada Sel, 17 Sep 2024 19.55, Jan Pánek ***@***.***> menulis:

**Comment by honzaap** [comment]
I'm sorry but that does not help at all, what do you mean create dataset? Do you mean like export the route or something like that?
